apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: altinity-demo
  namespace: clickhouse-lab
spec:
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              resources:
                requests:
                  cpu: "500m"
                  memory: "1Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
              ports:
                - name: http
                  containerPort: 8123
                - name: native
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
            - name: metrics-exporter
              image: altinity/metrics-exporter:latest
              resources:
                requests:
                  cpu: "100m"
                  memory: "100Mi"
                limits:
                  cpu: "250m"
                  memory: "256Mi"
              ports:
                - name: metrics
                  containerPort: 8888
    volumeClaimTemplates:
      - name: clickhouse-storage
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
          storageClassName: standard
    serviceTemplates:
      - name: clickhouse-service
        generateName: "chi-"
        spec:
          ports:
            - name: http
              port: 8123
            - name: native
              port: 9000
            - name: interserver
              port: 9009
          type: ClusterIP
      - name: clickhouse-metrics-service
        generateName: "clickhouse-metrics"
        spec:
          type: ClusterIP
          ports:
            - name: metrics
              port: 8888
  configuration:     
    clusters:
      - name: cluster-1
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-pod-template
          volumeClaimTemplate: clickhouse-storage
          serviceTemplate: clickhouse-service
          serviceTemplates: 
            - clickhouse-metrics-service
    zookeeper:
      nodes:
        - host: keeper-clickhouse-keeper.clickhouse-lab.svc.cluster.local
          port: 2181
